include:
  - project: exploit/k8s/utils/k8s-deploy
    file: /.k8s-ci.yml

image: docker

cache:
  paths:
    - target

stages:
  - docker
  - k8s-pipeline

build:
  stage: docker
  before_script:
    - apk add --no-cache git make
    - make docker-registry-login
  services:
    - docker:dind
  script:
    - make docker-build
    - make docker-push-registry
